# -*- coding: utf-8 -*-
"""Python基礎課題015

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1OW_QuH5XvPIbmeJAxQd4NFQnRihGt0AC
"""

# 課題　　Pythonでクラスを使ったプログラムが書けるようになること。
# 属性とメソッドについて理解すること。
# 名前(name)と年齢(age)の属性を持つHumanクラスを作成してください。
# nameとageを標準出力(print)するメソッド(printinfo)を追加してください。
# Humanクラスのインスタンスは、変数に代入してプログラム内で使用してください。

class Human:
  # コンストラクタの定義
  def __init__(self, name, age):
    # 属性を定義する
    self.name = name
    self.age = age

  def printinfo(self):
      print(f"名前は{self.name}、年齢は{self.age}です。")

# Humanクラスのインスタンスを作成
human1 = Human("侍太郎", 20)

human1.printinfo()