# -*- coding: utf-8 -*-
"""Python基礎課題008

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1--K_JwYOx5OzYMSgTC0MQGKvf7049ymY
"""

# 課題　条件分岐のif分で処理を切り替えよう
# 課題内容　Pythonで条件分岐のプログラムをプログラムを書けるようになる事
# if文を用いて、以下の条件分岐をするコードを記述してください。値はprint関数で出力してください。
# ・変数varが、3の倍数の場合は「Fizz」を出力
# ・変数varが、5の倍数の場合は「Buzz」を出力
# ・変数varが、3の倍数と5の倍数の両方に該当する場合は「FizzBuzz」を出力
# ・上記のどの場合にも該当しない場合は、変数varの値を出力
# ただし、変数varは正の整数とします。

# ランダムな整数を利用するためにrandomモジュールをインポート
import random

# # 変数varに９〜１５までのランダムな整数を代入する
var = random.randint(9, 15)

# # 動作確認用
# var = 15

# 変数varを出力する
print(var)

# 条件分岐
if var % 3 == 0 and var % 5 == 0:
    print("FIzzBuzz")
elif var % 3 == 0:
    print("Fizz")
elif var % 5 == 0:
    print("Buzz")
else:
    print(var)