# -*- coding: utf-8 -*-
"""Python基礎課題013

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1tnin0bFKf9EQ1BA71f9juBXH1W7R869z
"""

# 課題　商品購入時の消費税を関数で計算するプログラム
# 商品を購入して消費税を加えた計算結果を返す関数を記述する
# 第１引数に商品の金額、第２引数に消費税（１０％）を設定
# 計算結果で小数点が含まれる場合はそのまま表示　切り捨てや四捨五入などの処理は不要

def add_two_arguments(price, taxrate):
    # 消費税額を計算し変数に代入する
    consumption_tax = price * taxrate
    # 消費税を加えた合計額を返す
    return price + consumption_tax

    # 変数totalを出力する
    print(f"{total}円")

# 関数を呼び出し、引数として商品金額と消費税率を渡す
add_two_arguments(10000, 0.1)