# -*- coding: utf-8 -*-
"""python-basic-kadai-kadai_005

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1QvYPc-0yyI3ud5PHBAn-ASaIAT8K9Djf
"""

# Python基礎　課題005
# 課題　変数を使って四則演算しよう
# 台形の面積の計算結果を出力するプログラム
# 課題の内容
# 上辺：10cm
# 下辺：20cm
# 高さ：5cm
# 公式：台形の面積 =（上辺＋下辺）× 高さ ÷ 2
top_side = 10
bottom_side = 20
height = 5
trapezoid_area = (top_side + bottom_side) * height // 2
print(f"台形の面積は{trapezoid_area}㎠です")