# -*- coding: utf-8 -*-
"""Python基礎課題014

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1UolZnPK_IqT7x62CoQK1ETIemCWF4yRu
"""

# 課題　　グローバルスコープとローカルスコープの違いを理解すること。
# スコープを意識したプログラムが書けるようになること。

price1 = 100
price2 = 200

# taxの変数をグローバルスコープに定義
tax = 1.1

def total():

    return price1 + price2

print (total() * tax)