# -*- coding: utf-8 -*-
"""Python基礎課題017

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1FIXv4fjM9C4C--sm3pnAu8NLOEVD_wjm
"""

# 課題
# Humanインスタンスが成人かどうかチェックするプログラム
# 名前(name)と年齢(age)の属性を持つHumanクラスを作成
# Humanクラスには、以下の条件で標準出力(print)するcheck_adultメソッドを追加
# 　・ageが20以上の場合に大人であること
# 　・そうでない場合に大人でないこと
# Humanクラスのインスタンスを複数生成してリストに追加し、リストの要素数分だけcheck_adultメソッドを呼び出す
# 「リスト・ディクショナリ」「条件分岐」「繰り返し処理」「関数」「変数のスコープ」「クラス」を用いて、「課題の内容」の仕様通りのプログラムが記述する

class Human:
  def __init__(self, name, age):
      self.name = name
      self.age = age

  def check_adult(self):
      if self.age >= 20:
          print(f"{self.name}さんは大人です。")
      else:
          print(f"{self.name}さんは大人ではありません。")

  #Humanクラスのインスタンスを複数生成してリストに追加
  Humans = [
      Human("阪神太郎", 38),
      Human("阪急二郎", 21),
      Human("近鉄一郎", 20),
      Human("近鉄二郎", 18),
      Human("近鉄三郎", 19),
  ]

  # check_adultメソッドの呼び出し
  for Human in Humans:
      Human.check_adult()