# -*- coding: utf-8 -*-
"""Python基礎課題０１１

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1gk-Gqzqd5f9aTq5abSB19tTewcCwwD4N
"""

# 課題
# Pythonで繰り返し構文（for / while）のプログラムが書けるようになること。
# forとwhileの違いを理解すること。
list = ["水", "金", "地", "火", "木", "土", "天", "海", "冥"]

# リスト内の要素を順番に取得
for i in list:
    print(i)

# 変数iを初期化
i = 0
# 変数 i がリストの要素数より小さい間、処理を繰り返す
while i < len(list):
    print(list[i])
    i += 1